### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by koo5** [okrad/svelte-progressbar#20] opened 2021-01-29 23:46 UTC
i get this in my sapper app, when the component that the progress bar is in is redraws or something:

```Uncaught (in promise) TypeError: T is undefined
    q index.mjs:1
    o index.mjs:1
    transition_out index.mjs:816
    outro Campaign.1afc9597.js:1805
    transition_out index.mjs:816
    outro Campaign.1afc9597.js:2444
    transition_out index.mjs:816
    outro Campaigns.e689c8af.js:6789
    transition_out index.mjs:816
    o swiper-slide.js:61
    transition_out index.mjs:816
    o swiper-slide.js:212
    transition_out index.mjs:816
    outro Campaigns.e689c8af.js:7065
    transition_out index.mjs:816
    o swiper.js:330
    transition_out index.mjs:816
    outro Campaigns.e689c8af.js:7163
    transition_out index.mjs:816
    outro Campaigns.e689c8af.js:7274
    transition_out index.mjs:816
    outro SubscribedItemsInner.5b63f067.js:90
    transition_out index.mjs:816
    update SubscribedItemsInner.5b63f067.js:250
    update index.mjs:764
    flush index.mjs:732
    promise callback*schedule_update index.mjs:707
    make_dirty index.mjs:1442
    ctx index.mjs:1478
    7 client.0dfb4982.js:19031
    set index.mjs:35
    set svelte-shared-store.js:67
    input4_change_handler client.0dfb4982.js:3438
    listen index.mjs:238
    listen_dev index.mjs:1609
    mount client.0dfb4982.js:3351
    mount_component index.mjs:1412
    mount client.0dfb4982.js:3723
    mount client.0dfb4982.js:2674
    mount client.0dfb4982.js:2024
    mount_component index.mjs:1412
    mount client.0dfb4982.js:2613
    update client.0dfb4982.js:2803
    update index.mjs:764
    flush index.mjs:732
    promise callback*schedule_update index.mjs:707
    make_dirty index.mjs:1442
    ctx index.mjs:1478
    setOpen client.0dfb4982.js:2870
    eventClick index.svelte:56
    listen index.mjs:238
    listen_dev index.mjs:1609
    mount client.0dfb4982.js:2770
    mount_component index.mjs:1412
    mount client.0dfb4982.js:4222
    mount_component index.mjs:1412
    mount client.0dfb4982.js:18845
    mount client.0dfb4982.js:1436
    mount_component index.mjs:1412
    mount client.0dfb4982.js:18660
    mount client.0dfb4982.js:18974
    mount_component index.mjs:1412
    mount client.0dfb4982.js:19680
    mount_component index.mjs:1412
    init index.mjs:1501
    App client.0dfb4982.js:19786
    render app.mjs:424
    fulfilled app.mjs:25
    promise callback*step app.mjs:27
    1 app.mjs:28
    __awaiter$1 app.mjs:24
    render app.mjs:408
    1 app.mjs:403
    fulfilled app.mjs:25
    promise callback*step app.mjs:27
    1 app.mjs:28
    __awaiter$1 app.mjs:24
    handle_target$1 app.mjs:389
    navigate app.mjs:207
    1 app.mjs:28
    __awaiter$1 app.mjs:24
    navigate app.mjs:195
    load_current_page app.mjs:58
    promise callback*load_current_page app.mjs:53
    start$1 app.mjs:357
```

**Comment by okrad** [comment] 2021-02-23 15:19
Hi @koo5, I think it's a duplicate of #18, which should be solved with the new release. 
Can you confirm your issue is solved too?

**Closed** 2023-03-22 22:36 UTC
